### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by copycatcodex** [Widiskel/catopia-bot#3]
Can the feature be added to automatically sell pets and buy new land using gems if there are enough gems?
🤔🤔

**Comment by Widiskel** [comment]
for sell pet, i can but better not add that because leveling up a pet is still important, because your level is based on your pet highest level. so user need to focus on leveling up any pet they want, if i add auto sell pet feature and all pet sold , user cannot increase they level.
about buy land too, it about strategy, some user might focus on only collecting gems before the beta ends. (cause gems will be converted to rcat) if the gems is spended for buying land and snapshoot taken while the user only have few gems, i think its bad for them.

**Comment by copycatcodex** [comment]
Oh I see, how about adding to the list of pets that we have? like 
A : lv.2 3 | continued dancing, but it seemed less effective

**Comment by Widiskel** [comment]
i can, but it will take so much space on screen.

also i think that not important, because the bot will auto upgrade pet with same name same level and have more than 5 quantity.
